<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title><?=$this->blog_title?></title>
    <style type="text/css">
         @import url(http://fonts.googleapis.com/css?family=Lobster);
        body {
            font-size   : 14pt;
            color       : rgba(17, 76, 131, 0.80);
            line-height : 28px;
        }
        a, a:visited {
            color : #60a21c;
        }
        a:hover {
            color : #ffa13f;
        }
        h1{
          font-family: 'Lobster', cursive;
          font-weight: bold;
        }
        footer{
          font-size   : 12pt;
        }
   	</style>
</head>
<body>
  <header>
      <h1><?php echo $this->blog_title?></h1>
  </header>
  <hr/>
  <?php echo $this->blog_content?>
  <hr/>
  <footer>
        <p><?php echo $this->blog_footer ?> Now that you're up and running, it's time to start creating!
          Here are some links to help you get started:
        </p>

        <ul class="out-links">
          <li><a href="http://pimf-framework.de" target="_blank">Official Website</a></li>
          <li><a href="https://github.com/gjerokrsteski/pimf-framework/wiki" target="_blank">Learning PIMF</a></li>
          <li><a href="https://github.com/gjerokrsteski/pimf-blog-mysql" target="_blank">GitHub Repository</a></li>
          <li><a href="http://slides.com/gjerokrsteski/pimf-php-micro-framework/" target="_blank">PIMF Presentation</a></li>
        </ul>
  </footer>
</body>
</html>
